// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MoveProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MoveProto.proto</summary>
public static partial class MoveProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for MoveProto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MoveProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9Nb3ZlUHJvdG8ucHJvdG8iOAoLTW92ZU1lc3NhZ2USDQoFUHJvdG8YASAB",
          "KAUSDAoEUG9zWBgCIAEoBRIMCgRQb3NZGAMgASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MoveMessage), global::MoveMessage.Parser, new[]{ "Proto", "PosX", "PosY" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class MoveMessage : pb::IMessage<MoveMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MoveMessage> _parser = new pb::MessageParser<MoveMessage>(() => new MoveMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MoveMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MoveProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MoveMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MoveMessage(MoveMessage other) : this() {
    proto_ = other.proto_;
    posX_ = other.posX_;
    posY_ = other.posY_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MoveMessage Clone() {
    return new MoveMessage(this);
  }

  /// <summary>Field number for the "Proto" field.</summary>
  public const int ProtoFieldNumber = 1;
  private int proto_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Proto {
    get { return proto_; }
    set {
      proto_ = value;
    }
  }

  /// <summary>Field number for the "PosX" field.</summary>
  public const int PosXFieldNumber = 2;
  private int posX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PosX {
    get { return posX_; }
    set {
      posX_ = value;
    }
  }

  /// <summary>Field number for the "PosY" field.</summary>
  public const int PosYFieldNumber = 3;
  private int posY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PosY {
    get { return posY_; }
    set {
      posY_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MoveMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MoveMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Proto != other.Proto) return false;
    if (PosX != other.PosX) return false;
    if (PosY != other.PosY) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Proto != 0) hash ^= Proto.GetHashCode();
    if (PosX != 0) hash ^= PosX.GetHashCode();
    if (PosY != 0) hash ^= PosY.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Proto != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Proto);
    }
    if (PosX != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PosX);
    }
    if (PosY != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PosY);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Proto != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Proto);
    }
    if (PosX != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PosX);
    }
    if (PosY != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PosY);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Proto != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Proto);
    }
    if (PosX != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosX);
    }
    if (PosY != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosY);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MoveMessage other) {
    if (other == null) {
      return;
    }
    if (other.Proto != 0) {
      Proto = other.Proto;
    }
    if (other.PosX != 0) {
      PosX = other.PosX;
    }
    if (other.PosY != 0) {
      PosY = other.PosY;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Proto = input.ReadInt32();
          break;
        }
        case 16: {
          PosX = input.ReadInt32();
          break;
        }
        case 24: {
          PosY = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Proto = input.ReadInt32();
          break;
        }
        case 16: {
          PosX = input.ReadInt32();
          break;
        }
        case 24: {
          PosY = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
